name: Extract and Save Python Documentation

on:
  push:
    branches:
      - '**'  # Change this to your target branch

jobs:
  extract_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      - name: Install required Python packages
        run: |
          pip install -r requirements.txt  # Create a requirements.txt file with necessary packages
        working-directory: ${{ github.workspace }}

      - name: Extract and Save Documentation
        run: |
          # Find all Python files
          find . -name "*.py" | while read -r file; do
            # Extract documentation using a tool like Sphinx
            python -m sphinx.ext.apidoc -o docs $file
          done

          # Build the Sphinx documentation to HTML (you can adjust this to your preferred format)
          make html -C docs

          # Convert HTML documentation to Markdown using pandoc
          pandoc -s docs/_build/html/index.html -o docs.md

          # Commit and push the changes back to the repository
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add docs.md
          git commit -m "Update documentation"
          git push origin ${{ github.ref }}

        working-directory: ${{ github.workspace }}
